### ISSUE TITLE
elinks in termux segfaults at this site

### ISSUE THREAD

**Issue by Quasic** [termux/termux.github.io#34] opened 2017-10-19 03:24 UTC
Again, I'm writing this from elinks in termux. As I mentioned in termux/termux-packages#1682, whenever I try to visit termux.com or termux.github.io in elinks, it segfaults. I don't know if it is a problem with this site, or with elinks.

**Comment by sdrausty** [comment] 2017-10-19 09:04
@Quasic but only on `elinks https://termux.com` not with `elinks termux.com` correct?

![screenshot_20171019-050350](https://user-images.githubusercontent.com/27742457/31762996-eddfdec6-b48a-11e7-83e8-6b4ca0e795ce.png)

**Comment by fornwall** [comment] 2017-10-19 10:19
Closing this in favour of https://github.com/termux/termux-packages/issues/1682, as a segfault means that the problem is in the package, not the site.

**Closed by fornwall** 2017-10-19 10:19 UTC
